spring:
  output:
    ansi:
      enabled: always
  config:
    import: optional:secret.yml

  sql:
    init:
      platform: postgresql
      mode: always

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop


debug: true
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR
        security: TRACE